### ISSUE TITLE
Handheld dispensers sometimes hit the person firing them

### ISSUE THREAD

**Issue by ghost** [The-Fireplace/Fires-Random-Things#10]
In random angle dispenser will hit myself. I think, the problem with the point of starting projectile. Sometime it behind thrower or in him and damage themself. And the accuracy is terrible. The projectile fly around crosshair by 1 m.
I'm not good in english but I think the problem described intelligibly.

**Comment by The-Fireplace** [comment]
I'll look in to projectiles hitting the player who fires them. And accuracy is terrible on purpose, I'm not changing that.

**Comment by The-Fireplace** [comment]
Forge is no longer being supported, if I update this mod it will be rewritten and only support Fabric going forward. [Here's why](https://gist.github.com/The-Fireplace/d092f25e892a46902ecdec68dee2b938).
