### ISSUE TITLE
ElectroBlob's magic seeds get rejected

### ISSUE THREAD

**Issue by ghost** [The-Fireplace/Fires-Random-Things#14]
When I plant ElectroBlob's magic seeds they get unplanted, presumably when they try growing the first time. They work on other soil, and can be bonemealed.
(Note the seeds aren't part of ElectroBlob basic.)

**Comment by The-Fireplace** [comment]
Forge is no longer being supported, if I update this mod it will be rewritten and only support Fabric going forward. [Here's why](https://gist.github.com/The-Fireplace/d092f25e892a46902ecdec68dee2b938).
